import { AuditReport, BenchmarkItem, SkillItem } from "./types";

export const SAMPLE_AUDITS: Record<string, AuditReport> = {
  "adobe.com": {
    site: "https://www.adobe.com",
    audited_at: "2026-09-08T00:15:00Z",
    summary: {
      acpi_score: 91.4,
      crs_score: 88.5,
      total_findings: 4,
      critical: 0,
      high: 1,
      medium: 2,
      low: 1,
      component_scores: {
        crawlability: 96.0,
        renderability: 92.0,
        entity_clarity: 94.0,
        quotability: 86.0,
        trust_freshness: 90.0,
        orientation: 92.0,
        intent_continuity: 88.0,
        readability: 85.0,
        actionability: 89.0,
      },
    },
    findings: [
      {
        id: "geo-ent-sameas-wikidata",
        category: "structured_entity",
        title: "Wikidata Entity Disambiguation Missing in Root Graph",
        description: "Adobe Organization Schema contains official website and social links, but lacks direct sameAs claim to Wikidata Q11463.",
        severity: "medium",
        score_impact: -5.0,
        confidence: "high",
        evidence: {
          target: "script[type='application/ld+json']",
          snippet: `"@type": "Organization", "name": "Adobe Inc.", "sameAs": ["https://twitter.com/Adobe"]`,
        },
        suggested_action: {
          title: "Inject Authoritative Wikidata URI to sameAs",
          code_patch: `{\n  "@context": "https://schema.org",\n  "@type": "Organization",\n  "@id": "https://www.adobe.com/#organization",\n  "name": "Adobe",\n  "sameAs": [\n    "https://www.wikidata.org/wiki/Q11463",\n    "https://en.wikipedia.org/wiki/Adobe_Inc."\n  ]\n}`,
          explanation: "Adding Wikidata Q11463 allows Perplexity, Gemini, and ChatGPT knowledge graphs to instantly link Adobe products to verified enterprise ontology.",
        },
      },
      {
        id: "geo-aeo-table-accessibility",
        category: "aeo_quotability",
        title: "Comparison Tables Omit Explicit THEAD Scope Attributes",
        description: "Feature comparison tables in Creative Cloud landing sub-pages lack explicit scope='col' on table headers, degrading AI agent tabular quotability.",
        severity: "low",
        score_impact: -3.6,
        confidence: "medium",
        evidence: {
          target: "table.pricing-matrix",
          snippet: `<table><tr><td>Plan</td><td>Price</td></tr>...</table>`,
        },
        suggested_action: {
          title: "Use Semantic THEAD with Scope Headers",
          code_patch: `<thead>\n  <tr>\n    <th scope="col">Plan Tier</th>\n    <th scope="col">Monthly Price</th>\n    <th scope="col">Enterprise Cloud</th>\n  </tr>\n</thead>`,
          explanation: "LLM crawlers parse tabular facts 4.2x more reliably when semantic <thead> and scope attributes are explicitly defined.",
        },
      },
    ],
  },
  "linear.app": {
    site: "https://linear.app",
    audited_at: "2026-09-08T00:18:00Z",
    summary: {
      acpi_score: 87.2,
      crs_score: 94.0,
      total_findings: 3,
      critical: 0,
      high: 1,
      medium: 1,
      low: 1,
      component_scores: {
        crawlability: 98.0,
        renderability: 90.0,
        entity_clarity: 82.0,
        quotability: 84.0,
        trust_freshness: 82.0,
        orientation: 98.0,
        intent_continuity: 96.0,
        readability: 91.0,
        actionability: 92.0,
      },
    },
    findings: [
      {
        id: "geo-crawl-ai-allow",
        category: "crawl_render",
        title: "Explicit AI Bot Permissions Fully Allowed",
        description: "robots.txt explicitly permits GPTBot, ClaudeBot, and PerplexityBot with unrestricted access to public product docs.",
        severity: "info",
        score_impact: 0.0,
        confidence: "high",
        evidence: {
          target: "https://linear.app/robots.txt",
          snippet: "User-agent: GPTBot\nAllow: /\nUser-agent: ClaudeBot\nAllow: /",
        },
        suggested_action: {
          title: "Maintain Clear AI Crawler Policies",
          explanation: "Clear crawler allowlist ensures real-time model synthesis and up-to-date documentation citations in Claude Code and ChatGPT Search.",
        },
      },
    ],
  },
  "react-spa-sample.internal": {
    site: "https://spa-unrendered.sample",
    audited_at: "2026-09-08T00:20:00Z",
    summary: {
      acpi_score: 34.2,
      crs_score: 41.0,
      total_findings: 6,
      critical: 2,
      high: 2,
      medium: 1,
      low: 1,
      component_scores: {
        crawlability: 80.0,
        renderability: 20.0,
        entity_clarity: 25.0,
        quotability: 18.0,
        trust_freshness: 30.0,
        orientation: 45.0,
        intent_continuity: 40.0,
        readability: 50.0,
        actionability: 35.0,
      },
    },
    findings: [
      {
        id: "geo-crawl-hydration-gap",
        category: "crawl_render",
        title: "Severe Client-Side Hydration Gap Detected",
        description: "Raw HTML body contains only 38 words while mounting React bundle. AI search crawlers without full headless JS rendering index an empty white page.",
        severity: "critical",
        score_impact: -35.0,
        confidence: "high",
        evidence: {
          target: "div#root",
          snippet: `<body><div id="root"></div><script src="/bundle.js"></script></body>`,
        },
        suggested_action: {
          title: "Implement Server-Side Rendering (SSR) or Static Site Generation (SSG)",
          code_patch: `// Before: Client only SPA\n// After: Next.js Server Component or Cloudflare Worker SSR\nexport default async function Page() {\n  return (\n    <main>\n      <h1>Enterprise AI Readiness Audit</h1>\n      <p>Pre-rendered text available to all LLM crawlers without JS.</p>\n    </main>\n  );\n}`,
          explanation: "Search bots like PerplexityBot and ClaudeBot prioritize fast static DOM streams. SSR guarantees 100% indexing parity.",
        },
      },
    ],
  },
};

export const BENCHMARK_FIXTURES: BenchmarkItem[] = [
  {
    id: "BM-01",
    name: "AI Crawler Blockade",
    description: "Evaluates robots.txt rejecting GPTBot, ClaudeBot, and PerplexityBot.",
    architecture: "Static + Disallow Rules",
    category: "Crawl & Permissions",
    expected_acpi: "< 40",
    expected_crs: "Neutral",
    actual_acpi: 38.5,
    actual_crs: 72.0,
    key_finding: "robots_disallow (Critical)",
    status: "pass",
    fixture_file: "crawler_blocked.html",
  },
  {
    id: "BM-02",
    name: "Pure SPA Hydration Gap",
    description: "Empty <div id='root'> with heavy JavaScript bundle and zero SSR.",
    architecture: "Client-rendered React SPA",
    category: "Render & Hydration",
    expected_acpi: "< 40",
    expected_crs: "< 50",
    actual_acpi: 32.1,
    actual_crs: 44.0,
    key_finding: "hydration_gap (Critical)",
    status: "pass",
    fixture_file: "hydration_spa.html",
  },
  {
    id: "BM-03",
    name: "Next.js Server-Side Rendered",
    description: "Pre-rendered semantic HTML with fast hydration and clean DOM.",
    architecture: "Next.js Pages SSR",
    category: "Render & Hydration",
    expected_acpi: "> 75",
    expected_crs: "> 70",
    actual_acpi: 84.6,
    actual_crs: 79.2,
    key_finding: "Optimal SSR stream (High)",
    status: "optimal",
    fixture_file: "next-ssr.html",
  },
  {
    id: "BM-04",
    name: "Next.js App Router (RSC)",
    description: "React Server Components with zero hydration overhead on static text.",
    architecture: "Next.js 15 App Router RSC",
    category: "Render & Hydration",
    expected_acpi: "> 80",
    expected_crs: "> 75",
    actual_acpi: 89.2,
    actual_crs: 82.5,
    key_finding: "Zero-bundle static content",
    status: "optimal",
    fixture_file: "next-rsc.html",
  },
  {
    id: "BM-05",
    name: "Missing & Broken Structured Schema",
    description: "Malformed JSON-LD with missing closing brackets and zero entity links.",
    architecture: "Broken Schema.org",
    category: "Structured Entity",
    expected_acpi: "Penalty (-30)",
    expected_crs: "Neutral",
    actual_acpi: 46.8,
    actual_crs: 75.0,
    key_finding: "jsonld_syntax_error (High)",
    status: "pass",
    fixture_file: "bad_structured.html",
  },
  {
    id: "BM-06",
    name: "Authoritative Organization Graph",
    description: "Complete Schema.org @graph with sameAs Wikidata, Wikipedia, and LinkedIn.",
    architecture: "Semantic Graph Entity",
    category: "Structured Entity",
    expected_acpi: "> 85",
    expected_crs: "> 75",
    actual_acpi: 93.4,
    actual_crs: 81.0,
    key_finding: "Entity disambiguated (Optimal)",
    status: "optimal",
    fixture_file: "good_structured.html",
  },
  {
    id: "BM-07",
    name: "Dense Atomic Quotability (AEO)",
    description: "High factual claim density with question headings and structured tables.",
    architecture: "Knowledge-Dense Article",
    category: "AEO Quotability",
    expected_acpi: "> 80",
    expected_crs: "> 70",
    actual_acpi: 88.7,
    actual_crs: 77.4,
    key_finding: "High quotability index",
    status: "optimal",
    fixture_file: "strong_aeo.html",
  },
  {
    id: "BM-08",
    name: "Marketing Fluff & Low Quotability",
    description: "Vague adjectives, zero verifiable figures, missing headers.",
    architecture: "Fluff Landing Page",
    category: "AEO Quotability",
    expected_acpi: "< 45",
    expected_crs: "< 45",
    actual_acpi: 41.2,
    actual_crs: 39.8,
    key_finding: "Low atomic density (High)",
    status: "pass",
    fixture_file: "weak_aeo.html",
  },
  {
    id: "BM-09",
    name: "Temporal Decay & Stale Content",
    description: "Content untouched since 2021 with outdated copyright timestamps.",
    architecture: "Unmaintained Blog",
    category: "Freshness & Trust",
    expected_acpi: "< 50",
    expected_crs: "Neutral",
    actual_acpi: 47.3,
    actual_crs: 68.0,
    key_finding: "temporal_decay (Medium)",
    status: "pass",
    fixture_file: "stale_article.html",
  },
  {
    id: "BM-10",
    name: "Live Corroborated Freshness",
    description: "Recent 2026 timestamps, author editorial byline, active contact links.",
    architecture: "Authoritative Publication",
    category: "Freshness & Trust",
    expected_acpi: "> 80",
    expected_crs: "> 80",
    actual_acpi: 91.0,
    actual_crs: 86.4,
    key_finding: "Freshness corroborated",
    status: "optimal",
    fixture_file: "current_article.html",
  },
  {
    id: "BM-11",
    name: "High Friction & Wall-of-Text",
    description: "250-word unbroken paragraphs, no H1, missing primary action CTA.",
    architecture: "Unformatted Longform",
    category: "Engagement & Retention",
    expected_acpi: "Neutral",
    expected_crs: "< 40",
    actual_acpi: 65.0,
    actual_crs: 36.2,
    key_finding: "bounce_risk_high (High)",
    status: "pass",
    fixture_file: "weak_engagement.html",
  },
  {
    id: "BM-12",
    name: "Optimized Hero & Reading Flow",
    description: "Concise H1 (<7 words), 25-word subhead, high-contrast primary CTA.",
    architecture: "High-Converting Hero",
    category: "Engagement & Retention",
    expected_acpi: "> 75",
    expected_crs: "> 85",
    actual_acpi: 82.0,
    actual_crs: 92.8,
    key_finding: "Optimal Retention Flow",
    status: "optimal",
    fixture_file: "strong_engagement.html",
  },
  {
    id: "BM-13",
    name: "Technical Documentation Layout",
    description: "Breadcrumb navigation, code samples, API endpoint tables.",
    architecture: "Developer Documentation",
    category: "AEO Quotability",
    expected_acpi: "> 80",
    expected_crs: "> 75",
    actual_acpi: 87.5,
    actual_crs: 81.2,
    key_finding: "Technical readability high",
    status: "optimal",
    fixture_file: "documentation.html",
  },
  {
    id: "BM-14",
    name: "Navigation Noise vs Content Ratio",
    description: "Massive mega-menu (800 DOM nodes) with minimal main body copy.",
    architecture: "Bloated Enterprise Portal",
    category: "Render & Hydration",
    expected_acpi: "< 60",
    expected_crs: "< 55",
    actual_acpi: 54.0,
    actual_crs: 48.6,
    key_finding: "low_content_to_dom_ratio",
    status: "pass",
    fixture_file: "navigation_noise.html",
  },
];

export const MARKETPLACE_SKILLS: SkillItem[] = [
  {
    id: "audit-orchestrator",
    name: "OmniAudit Master Orchestrator",
    entrypoint: true,
    version: "1.0.0",
    description: "Master dispatcher that executes specialist audit skills, aggregates findings into standardized JSON schema, and computes ACPI and CRS scores.",
    path: "skills/audit-orchestrator",
    input_schema: "{ 'url': 'string', 'output': 'optional string' }",
    output_schema: "references/audit_schema.json",
    execution_time_ms: 124,
    tags: ["Entrypoint", "Orchestrator", "ACPI", "CRS", "Schema Validator"],
  },
  {
    id: "crawl-render-audit",
    name: "AI Bot Crawler & Hydration Inspector",
    version: "1.0.0",
    description: "Evaluates robots.txt AI permissions (GPTBot, ClaudeBot, PerplexityBot) and detects client-side hydration gaps in modern JS SPAs.",
    path: "skills/crawl-render-audit",
    input_schema: "{ 'url': 'string', 'html': 'string', 'robots_txt': 'string' }",
    output_schema: "Array<Finding>",
    execution_time_ms: 38,
    tags: ["Crawlability", "robots.txt", "Hydration Gap", "Next.js", "Nuxt"],
  },
  {
    id: "structured-entity-audit",
    name: "Schema.org & Knowledge Graph Disambiguator",
    version: "1.0.0",
    description: "Validates JSON-LD semantic markup, entity disambiguation links (sameAs to Wikidata/Wikipedia), and enterprise ontology.",
    path: "skills/structured-entity-audit",
    input_schema: "{ 'html': 'string' }",
    output_schema: "Array<Finding>",
    execution_time_ms: 22,
    tags: ["JSON-LD", "Wikidata", "sameAs", "Schema.org", "Knowledge Graph"],
  },
  {
    id: "aeo-quotability-audit",
    name: "LLM Quotability & Atomic Fact Scorer",
    version: "1.0.0",
    description: "Calculates atomic fact density, interrogative heading-answer pairs, and tabular accessibility for generative AI citations.",
    path: "skills/aeo-quotability-audit",
    input_schema: "{ 'html': 'string' }",
    output_schema: "Array<Finding>",
    execution_time_ms: 29,
    tags: ["AEO", "Quotability", "Atomic Facts", "Tables", "Q&A"],
  },
  {
    id: "freshness-corroboration-audit",
    name: "Temporal Signals & Trust Corroborator",
    version: "1.0.0",
    description: "Tracks temporal freshness, author editorial bylines, and organizational transparency signals to mitigate hallucination risks.",
    path: "skills/freshness-corroboration-audit",
    input_schema: "{ 'html': 'string' }",
    output_schema: "Array<Finding>",
    execution_time_ms: 18,
    tags: ["Freshness", "E-E-A-T", "Bylines", "Temporal Decay"],
  },
  {
    id: "on-site-engagement-audit",
    name: "Visitor Retention & Value Prop Evaluator",
    version: "1.0.0",
    description: "Analyzes above-the-fold value prop clarity, cognitive readability (Flesch-Kincaid), and CTA conversion readiness.",
    path: "skills/on-site-engagement-audit",
    input_schema: "{ 'html': 'string' }",
    output_schema: "Array<Finding>",
    execution_time_ms: 25,
    tags: ["Readability", "Hero Clarity", "Bounce Risk", "Retention"],
  },
];
